---
- name: Insstall Tomcat 9
  become: yes
  hosts: AppServer
  vars: 
    - username: tomcat
    - group: tomcat
    - default_shell: /bin/false
    - tomcat_home_dir: /opt/tomcat
    - tomcat_version: 9.0.76
  
  tasks:
    - name: Update apt repo & cache
      apt: 
        update_cache: yes

    - name: Install openjdk 11 
      package:
        name: "{{ java_package }}"
        state: present
    
    - name: Create a tomcat group
      ansible.builtin.group:
        name: "{{ username }}"
        state: present
    
    - name: Create a tomcat user
      ansible.builtin.user:
        name: "{{ username }}"
        group: "{{ username }}"
        shell: "{{ default_shell }}"
        home: "{{ tomcat_home_dir }}"
        create_home: yes
        state: present

    - name: Download Tomcat
      ansible.builtin.get_url:
        url: "https://dlcdn.apache.org/tomcat/tomcat-9/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz"
        dest: "/tmp/apache-tomcat-{{ tomcat_version }}.tar.gz"
    
    - name: Untar the file 
      ansible.builtin.unarchive:
        src: "/tmp/apache-tomcat-{{ tomcat_version }}.tar.gz"
        dest: "{{ tomcat_home_dir }}"
        remote_src: yes
    
    - name: Update Permissions
      ansible.builtin.file:
        path: "{{ tomcat_home_dir }}"
        owner: "{{ username }}"
        group: "{{ username }}"
        recurse: yes
        mode: '0755'
        state: directory
    
    - name: Create a sym-link
      ansible.builtin.file:
        src: "{{ tomcat_home_dir }}"
        owner: "{{ username }}"
        group: "{{ username }}"
        state: link
        
        

