---
- name: Install Tomcat 9
  become: yes
  hosts: AppServer
  vars: 
    - username: tomcat
    - group: tomcat
    - default_shell: /bin/false
    - tomcat_home_dir: /opt/tomcat
    - tomcat_latest: /opt/tomcat/latest
    - tomcat_bin_dir: /opt/tomcat/latest/bin
    - tomcat_service_location: /etc/systemd/system/tomcat.service
    - tomcat_version: 9.0.76
    - executables:
        - catalina.sh
        - ciphers.sh
        - configtest.sh
        - daemon.sh
        - digest.sh
        - makebase.sh
        - setclasspath.sh
        - shutdown.sh
        - startup.sh
        - tool-wrapper.sh
        - version.sh

  tasks:
    - name: Update apt repo & cache
      apt: 
        update_cache: yes

    - name: Install openjdk 11 
      package:
        name: "{{ java_package }}"
        state: present
    
    - name: Create a tomcat group
      ansible.builtin.group:
        name: "{{ username }}"
        state: present
    
    - name: Create a tomcat user
      ansible.builtin.user:
        name: "{{ username }}"
        group: "{{ username }}"
        shell: "{{ default_shell }}"
        home: "{{ tomcat_home_dir }}"
        create_home: yes
        state: present

    - name: Download Tomcat
      ansible.builtin.get_url:
        url: "https://dlcdn.apache.org/tomcat/tomcat-9/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz"
        dest: "/tmp/apache-tomcat-{{ tomcat_version }}.tar.gz"
    
    - name: Extract Tomcat
      ansible.builtin.unarchive:
        src: "/tmp/apache-tomcat-{{ tomcat_version }}.tar.gz"
        dest: "{{ tomcat_home_dir }}"
        creates: "{{ tomcat_home_dir }}/apache-tomcat-{{ tomcat_version }}"
        owner: "{{ username }}"
        group: "{{ username }}"
        remote_src: yes

    - name: Create a sym-link
      ansible.builtin.file:
        src: "{{ tomcat_home_dir }}/apache-tomcat-{{ tomcat_version }}"
        dest: "{{ tomcat_latest }}"
        owner: "{{ username }}"
        group: "{{ username }}"
        state: link

    - name: Change ownership
      ansible.builtin.file:
        path: "{{ tomcat_home_dir }}"
        owner: "{{ username }}"
        group: "{{ username }}"
        state: directory
        recurse: yes
    
    - name: Search executable files
      ansible.builtin.find:
        paths: "{{ tomcat_bin_dir }}"
        patterns: "*.sh"
        recurse: yes
      register: sh_files
  
    - name: Print all the files
      debug:
        var: sh_files
    
    - name: Make .sh files executables
      ansible.builtin.file:
        path: "{{ item.path }}"
        owner: foo
        group: foo
        mode: '0755'
      loop: "{{ sh_files }}"
      
 




        

