---
- name: Install LAMP
  become: yes
  hosts: WebServers
  
  tasks:
    - name: Update Debian packages
      apt: 
        update_cache: yes
      when: ansible_facts['os_family'] == "Debian"

    - name: Install Apache
      package:
        name: "{{ apache_package }}"
        state: present

    - name: Ensure httpd is running
      ansible.builtin.systemd:
        name: "{{ service }}"
        state: started
        enabled: yes
      when: ansible_facts['os_family'] == "RedHat"

    - name: Force all notified handlers to run at this point
      meta: flush_handlers

    - name: Install php
      package:
        name: "{{ item }}"
        state: present
      loop: "{{ php_packages }}"  
      notify:
        - Reload Apache service

    - name: Copy php file
      ansible.builtin.copy:
        src: 'info.php'
        dest: "{{ php_location }}"

  handlers:
    - name: Reload Apache service
      ansible.builtin.systemd:
        name: "{{ service }}"
        state: restarted
        enabled: yes

