---
- name: Install LAMP Stack
  become: yes
  hosts: WebServers
  
  tasks:
    - name: Update Ubuntu packages
      apt: 
        update_cache: yes
      when: ansible_facts['os_family'] == "Debian"

    - name: Install Apache
      package:
        name: "{{ apache_package }}"
        state: present
      notify:
        - Ensure Apache is enabled & started        

    - name: Install php
      package:
        name: "{{ item }}"
        state: present
      loop: "{{ php_packages }}"  
      notify:
        - Ensure Apache is enabled & started

    - name: Copy the php file
      ansible.builtin.copy:
        src: 'info.php'
        dest: "{{ php_location }}"
      notify:
        - Ensure Apache is enabled & started  

  handlers:
    - name: Ensure Apache is enabled & started
      ansible.builtin.service:
        name: "{{ apache_package }}"
        enabled: yes
        state: started

