---
- name: NodeJS Installations in Linux Distros
  become: yes
  hosts: AppServers
  
  tasks:
    - name: Update Ubuntu packages
      apt:
        update_cache: yes
      when: ansible_facts['os_family'] == "Debian"   
    
    - name: Install NodeJS on Ubuntu & RedHat
      package:
        name: "{{ package }}"
        state: present
