---
- name: NodeJS Installations in Linux Distros
  become: yes
  hosts: AppServers
  tasks:
    - name: Install NodeJS on Ubuntu & RedHat
      package:
        name: "{{ package }}"
        state: present