---
# handlers file for tomcat9
- name: Reload the daemon, enable and start the tomcat service
  ansible.builtin.systemd:
    name: 'tomcat.service'
    daemon_reload: yes
    enabled: yes
    state: restarted
