---
#tasks file for tomcat9
- include_tasks: setup-Debian.yml
  when: ansible_facts['os_family'] == "Debian"
- include_tasks: setup-Java.yml
- include_tasks: setup-tomcat.yml
- include_tasks: setup-deployment.yml

